name: Publish Extension

# events but only for the main branch
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Install Node.JS"
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: "Install Dependencies"
        run: npm install -g vsce
      - name: Publish to Marketplace
        run: vsce publish -p $VSCE_TOKEN
    env:
      VSCE_TOKEN: ${{ secrets.VSM_PAT }}