name: Add to releases
on:
  release:
    types: ['created', 'edited']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Install Node.JS"
        uses: actions/setup-node@v2
        with:
          node-version: 18.0.0
      - name: "Run CI"
        run: |
          npm ci
          npm run build
      - name: "Add to latest release"
        uses: softprops/action-gh-release@v1
        with:
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
